# Generated by Django 6.1 on 2026-08-18 12:20

import apps.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=apps.utils.today)),
                ('title', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, max_length=80)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('progress', models.CharField(choices=[('DONE', 'Done'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked')], default='DONE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
