# Generated by Django 6.1 on 2026-08-18 12:20

import datetime
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('start_time', models.TimeField(default=datetime.time(9, 0), help_text='Office start (9:00 AM)')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), help_text='Office end (6:00 PM)')),
                ('late_after', models.TimeField(default=datetime.time(10, 0), help_text='A punch after this time counts as LATE. Default 10:00 AM')),
                ('required_hours', models.DecimalField(decimal_places=2, default=9, help_text='Hours that must be completed each day (default 9)', max_digits=4)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4, help_text='Anything below this counts as a half day', max_digits=4)),
                ('min_out_gap_minutes', models.PositiveIntegerField(default=60, help_text='A second punch within this many minutes of the first is treated as a duplicate tap')),
                ('weekend_days', models.CharField(default='4,5', help_text='Weekly holidays: 0=Mon ... 6=Sun. Friday+Saturday = 4,5', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(help_text='Company employee code, e.g. EMP-001', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR / Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10)),
                ('rfid_card_no', models.CharField(blank=True, help_text='The number printed on the card, or read from the device', max_length=32, null=True, unique=True, verbose_name='RFID card ID')),
                ('device_user_id', models.CharField(blank=True, help_text='User ID stored inside the ZKTeco F18', max_length=16, null=True, unique=True)),
                ('card_issued_on', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('work_policy', models.CharField(choices=[('OFFICE', 'Office only'), ('HYBRID', 'Office + Home office'), ('REMOTE', 'Remote only')], default='OFFICE', max_length=10)),
                ('is_attendance_tracked', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.designation')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.shift')),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
