# Generated by Django 6.1 on 2026-08-18 12:21

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='extend_only_when_late',
            field=models.BooleanField(default=False, help_text='Off (default): required hours are always counted from the in-time. On: the required out time is only pushed back when the employee is late; anyone arriving within the grace period may leave at the normal end time.'),
        ),
    ]
