# Generated by Django 6.1 on 2026-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_shift_extend_only_when_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='duplicate_window_minutes',
            field=models.PositiveIntegerField(default=3, help_text='Two punches this close together are the same tap read twice, so the second one is ignored.'),
        ),
        migrations.AddField(
            model_name='shift',
            name='min_outing_minutes',
            field=models.PositiveIntegerField(default=5, help_text='A trip out of the office shorter than this is ignored - it is usually someone tapping the reader twice by mistake.'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='extend_only_when_late',
            field=models.BooleanField(default=False, help_text='Off (default): the required hours are always counted from the in-time. On: the required out time is only pushed back when the employee is late.'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='min_out_gap_minutes',
            field=models.PositiveIntegerField(default=60, help_text='No longer used - kept so old data is not lost.'),
        ),
    ]
