# Generated by Django 6.1 on 2026-08-18 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Gate F18', max_length=60)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=4370)),
                ('comm_password', models.CharField(blank=True, help_text='Device COMM key (leave blank if it is 0)', max_length=32)),
                ('timeout', models.PositiveIntegerField(default=10)),
                ('force_udp', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('clear_after_sync', models.BooleanField(default=False, help_text='Clear the device log after a successful sync (use with care)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('unmatched', models.PositiveIntegerField(default=0, help_text='Punches that matched no employee')),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='devices.device')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
