# Generated by Django 6.1 on 2026-08-18 12:20

import apps.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('is_optional', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('required_out', models.DateTimeField(blank=True, help_text='When the employee must leave to complete the required hours', null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_out_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('shortfall_minutes', models.PositiveIntegerField(default=0, help_text='How far short of the required hours')),
                ('status', models.CharField(choices=[('PRESENT', 'On time'), ('LATE', 'Late'), ('EARLY_OUT', 'Early out'), ('LATE_EARLY', 'Late + early out'), ('HALF_DAY', 'Half day'), ('MISSING_OUT', 'Out punch missing'), ('ABSENT', 'Absent'), ('LEAVE', 'On leave'), ('HOLIDAY', 'Holiday'), ('WEEKEND', 'Weekend')], default='ABSENT', max_length=12)),
                ('mode', models.CharField(choices=[('OFFICE', 'Office'), ('HOME', 'Home office'), ('LEAVE', 'Leave'), ('OFF', 'Off day')], default='OFFICE', max_length=8)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_out', models.BooleanField(default=False)),
                ('punch_count', models.PositiveSmallIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('is_manual_override', models.BooleanField(default=False, help_text='When set, the day is no longer recalculated automatically')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shift')),
            ],
            options={
                'verbose_name_plural': 'Daily attendance',
                'ordering': ['-date', 'employee__employee_id'],
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_a41095_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_attendance_per_day')],
            },
        ),
        migrations.CreateModel(
            name='HomeOfficeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=apps.utils.today)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Why you are working from home')),
                ('work_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('review_note', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_office_entries', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_home_office', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Home office entries',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_home_office_per_day')],
            },
        ),
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField()),
                ('card_no', models.CharField(blank=True, max_length=32)),
                ('device_user_id', models.CharField(blank=True, max_length=16)),
                ('source', models.CharField(choices=[('DEVICE', 'ZKTeco device'), ('MANUAL', 'Manual entry'), ('IMPORT', 'CSV import'), ('HOME', 'Home office')], default='DEVICE', max_length=10)),
                ('raw_status', models.SmallIntegerField(default=0)),
                ('is_matched', models.BooleanField(default=True, help_text='Whether the punch was matched to an employee')),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='devices.device')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-punch_time'],
                'indexes': [models.Index(fields=['employee', 'punch_time'], name='attendance__employe_eab805_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'punch_time'), name='uniq_punch_per_employee_time')],
            },
        ),
    ]
