# Generated by Django 6.1 on 2026-08-22 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='inside_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Time actually inside the office'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='outside_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total time spent out of the office during the day'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='outside_paid_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Of that, time out on office work'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='outside_unpaid_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Of that, personal time - it pushes the required out time back'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='trip_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many times the employee left and came back'),
        ),
        migrations.AddField(
            model_name='punchlog',
            name='direction',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('UNKNOWN', 'Not paired yet')], default='UNKNOWN', help_text='Odd punches of the day are IN, even punches are OUT', max_length=8),
        ),
        migrations.AddField(
            model_name='punchlog',
            name='is_ignored',
            field=models.BooleanField(default=False, help_text='A duplicate tap - not counted when pairing the day'),
        ),
        migrations.AddField(
            model_name='punchlog',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position of this punch within the day, starting at 1'),
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('left_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('purpose', models.CharField(choices=[('OFFICIAL', 'Official work'), ('PERSONAL', 'Personal'), ('BREAK', 'Break / meal'), ('UNSPECIFIED', 'Not stated yet')], default='UNSPECIFIED', max_length=12)),
                ('destination', models.CharField(blank=True, help_text='Where did you go?', max_length=120)),
                ('note', models.TextField(blank=True, help_text='What was it for?')),
                ('counts_as_work', models.BooleanField(default=True, help_text='Whether this time counts towards the working hours')),
                ('is_admin_adjusted', models.BooleanField(default=False, help_text='An admin set counts_as_work by hand')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outings', to='attendance.dailyattendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outings', to=settings.AUTH_USER_MODEL)),
                ('in_punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attendance.punchlog')),
                ('out_punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attendance.punchlog')),
            ],
            options={
                'ordering': ['-date', 'left_at'],
                'indexes': [models.Index(fields=['date', 'purpose'], name='attendance__date_6ff5f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'left_at'), name='uniq_outing_start')],
            },
        ),
    ]
